export const briefJsonSchema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  title: "Moki Alpha BriefDocument",
  type: "object",
  additionalProperties: false,
  required: [
    "schemaVersion",
    "slug",
    "metadata",
    "hero",
    "cta",
    "sections",
    "scenarioAnalysis",
    "monitoringDashboard",
    "sourceNote",
    "disclaimer",
  ],
  properties: {
    schemaVersion: { const: "0.1" },
    slug: { type: "string" },
    metadata: {
      type: "object",
      additionalProperties: true,
      required: [
        "ticker",
        "companyName",
        "title",
        "briefType",
        "language",
        "isMock",
        "generatedAt",
        "updatedAt",
        "frameworkName",
        "frameworkStatus",
        "dataMode",
        "brand",
        "product",
        "shareLabel",
      ],
      properties: {
        ticker: { type: "string" },
        companyName: { type: "string" },
        exchange: { type: "string" },
        title: { type: "string" },
        briefType: { type: "string" },
        language: { enum: ["zh-CN", "en-US"] },
        isMock: { const: true },
        generatedAt: { type: "string" },
        updatedAt: { type: "string" },
        frameworkName: { type: "string" },
        frameworkStatus: { const: "mock-reference-only" },
        dataMode: {
          enum: [
            "mock",
            "llm-demo-no-live-data",
            "evidence-draft",
          ],
        },
        brand: { const: "Moki" },
        product: { const: "Moki Alpha Brief" },
        shareLabel: { type: "string" },
      },
    },
    hero: {
      type: "object",
      additionalProperties: true,
      required: ["eyebrow", "headline", "subheadline", "badges", "metrics"],
      properties: {
        eyebrow: { type: "string" },
        headline: { type: "string" },
        subheadline: { type: "string" },
        badges: {
          type: "array",
          items: {
            type: "object",
            required: ["label", "tone"],
            properties: {
              label: { type: "string" },
              tone: { enum: ["brand", "neutral"] },
            },
          },
        },
        metrics: {
          type: "array",
          items: { $ref: "#/$defs/briefMetric" },
        },
      },
    },
    cta: {
      type: "object",
      additionalProperties: true,
      required: ["title", "description", "buttonLabel"],
      properties: {
        title: { type: "string" },
        description: { type: "string" },
        buttonLabel: { type: "string" },
        buttonHref: { type: "string" },
      },
    },
    sections: {
      type: "array",
      minItems: 10,
      items: { $ref: "#/$defs/section" },
    },
    scenarioAnalysis: {
      type: "object",
      additionalProperties: true,
      required: ["id", "order", "title", "description", "scenarios"],
      properties: {
        id: { const: "scenarios" },
        order: { type: "number" },
        title: { type: "string" },
        shortTitle: { type: "string" },
        description: { type: "string" },
        currentPrice: { type: "string" },
        probabilityWeightedTarget: { type: "string" },
        scenarios: {
          type: "array",
          minItems: 3,
          items: {
            type: "object",
            required: [
              "name",
              "label",
              "probability",
              "keyAssumptions",
              "targetPrice",
              "impliedReturn",
            ],
            properties: {
              name: { type: "string" },
              label: { type: "string" },
              probability: { type: "string" },
              keyAssumptions: { type: "string" },
              targetPrice: { type: "string" },
              impliedReturn: { type: "string" },
              tone: { enum: ["bull", "base", "bear"] },
              operatingSetup: { type: "string" },
              trigger: { type: "string" },
            },
          },
        },
      },
    },
    monitoringDashboard: {
      type: "object",
      additionalProperties: true,
      required: ["id", "order", "title", "description", "metrics"],
      properties: {
        id: { const: "monitoring-dashboard" },
        order: { type: "number" },
        title: { type: "string" },
        shortTitle: { type: "string" },
        description: { type: "string" },
        metrics: {
          type: "array",
          minItems: 3,
          items: {
            type: "object",
            required: ["metric", "whyItMatters", "threshold"],
            properties: {
              metric: { type: "string" },
              whyItMatters: { type: "string" },
              threshold: { type: "string" },
              status: {
                enum: ["Healthy", "Watch", "Caution", "Trigger"],
              },
              cadence: { type: "string" },
            },
          },
        },
      },
    },
    evidencePack: {
      type: "object",
      additionalProperties: true,
      properties: {
        asOf: { type: "string" },
        ticker: { type: "string" },
        dataMode: { const: "evidence-draft" },
        searchProvider: { enum: ["mock", "tavily"] },
        sources: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: true,
            required: ["id", "title", "retrievedAt", "confidence"],
            properties: {
              id: { type: "string" },
              title: { type: "string" },
              url: { type: "string" },
              domain: { type: "string" },
              publisher: { type: "string" },
              sourceType: { type: "string" },
              publishedAt: { type: "string" },
              retrievedAt: { type: "string" },
              confidence: { enum: ["high", "medium", "low"] },
              dateStatus: {
                enum: ["published", "retrieved-only", "unknown"],
              },
              qualityReason: { type: "string" },
              sourceRank: { type: "number" },
            },
          },
        },
        newsItems: { type: "array" },
        warnings: { type: "array", items: { type: "string" } },
      },
    },
    secEvidencePack: {
      type: "object",
      additionalProperties: true,
      properties: {
        asOf: { type: "string" },
        ticker: { type: "string" },
        cik: { type: "string" },
        companyName: { type: "string" },
        provider: { enum: ["mock", "sec"] },
        dataMode: { const: "evidence-draft" },
        fiscalFacts: { type: "array" },
        recentFilings: { type: "array" },
        sources: { type: "array" },
        warnings: { type: "array", items: { type: "string" } },
      },
    },
    irEvidencePack: {
      type: "object",
      additionalProperties: true,
      properties: {
        asOf: { type: "string" },
        ticker: { type: "string" },
        companyName: { type: "string" },
        provider: { enum: ["mock", "search"] },
        dataMode: { const: "evidence-draft" },
        irItems: { type: "array" },
        sources: { type: "array" },
        warnings: { type: "array", items: { type: "string" } },
      },
    },
    marketEvidencePack: {
      type: "object",
      additionalProperties: true,
      properties: {
        asOf: { type: "string" },
        ticker: { type: "string" },
        companyName: { type: "string" },
        provider: { enum: ["mock", "stock-api", "global-stock-data"] },
        dataMode: { const: "evidence-draft" },
        quote: { type: "object", additionalProperties: true },
        priceHistory: { type: "array" },
        sources: { type: "array" },
        providerChain: { type: "array", items: { type: "string" } },
        attemptedProviders: { type: "array", items: { type: "string" } },
        warnings: { type: "array", items: { type: "string" } },
      },
    },
    researchEvidenceContext: {
      type: "object",
      additionalProperties: true,
      properties: {
        asOf: { type: "string" },
        ticker: { type: "string" },
        companyName: { type: "string" },
        dataMode: { const: "evidence-draft" },
        evidenceLevel: {
          enum: [
            "none",
            "search-only",
            "sec-only",
            "ir-only",
            "market-only",
            "search-and-sec",
            "search-and-ir",
            "search-and-market",
            "sec-and-ir",
            "sec-and-market",
            "ir-and-market",
            "search-sec-and-ir",
            "search-sec-and-market",
            "search-ir-and-market",
            "sec-ir-and-market",
            "search-sec-ir-and-market",
          ],
        },
        sourceRegistry: { type: "array" },
        factLedger: { type: "array" },
        coverage: { type: "object", additionalProperties: true },
        warnings: { type: "array", items: { type: "string" } },
      },
    },
    evidenceSummary: {
      type: "object",
      additionalProperties: true,
      properties: {
        hasSearchEvidence: { type: "boolean" },
        hasSecEvidence: { type: "boolean" },
        hasMarketPrice: { type: "boolean" },
        hasMarketVolume: { type: "boolean" },
        hasMarketPriceHistory: { type: "boolean" },
        hasMarketCap: { type: "boolean" },
        hasConsensus: { const: false },
        hasCompanyIr: { type: "boolean" },
        hasEarningsRelease: { type: "boolean" },
        hasManagementCommentary: { type: "boolean" },
        hasGuidanceContext: { type: "boolean" },
        missing: { type: "array", items: { type: "string" } },
        warnings: { type: "array", items: { type: "string" } },
      },
    },
    sourceNote: {
      type: "object",
      additionalProperties: true,
      required: ["id", "title", "paragraphs"],
      properties: {
        id: { const: "source-note" },
        title: { type: "string" },
        paragraphs: {
          type: "array",
          minItems: 1,
          items: { type: "string" },
        },
      },
    },
    disclaimer: {
      type: "object",
      additionalProperties: true,
      required: ["text"],
      properties: {
        title: { type: "string" },
        text: { type: "string" },
      },
    },
  },
  $defs: {
    briefMetric: {
      type: "object",
      required: ["label", "value"],
      properties: {
        label: { type: "string" },
        value: { type: "string" },
        detail: { type: "string" },
      },
    },
    section: {
      type: "object",
      additionalProperties: true,
      required: ["id", "order", "title", "kind", "blocks"],
      properties: {
        id: { type: "string" },
        order: { type: "number" },
        title: { type: "string" },
        shortTitle: { type: "string" },
        eyebrow: { type: "string" },
        kind: {
          enum: [
            "executive-view",
            "company-snapshot",
            "industry-chain",
            "competitive-landscape",
            "financial-deep-dive",
            "value-drivers",
            "valuation",
            "variant-perception",
            "catalysts",
            "risks",
            "bottom-line",
          ],
        },
        summary: { type: "string" },
        blocks: {
          type: "array",
          minItems: 1,
          items: {
            oneOf: [
              {
                type: "object",
                required: ["type", "content"],
                properties: {
                  type: { const: "paragraph" },
                  content: { type: "string" },
                },
              },
              {
                type: "object",
                required: ["type", "items"],
                properties: {
                  type: { enum: ["bulletList", "orderedList"] },
                  items: { type: "array", items: { type: "string" } },
                },
              },
              {
                type: "object",
                required: ["type", "content"],
                properties: {
                  type: { const: "callout" },
                  title: { type: "string" },
                  content: { type: "string" },
                  tone: { enum: ["neutral", "brand", "risk"] },
                  label: { type: "string" },
                },
              },
              {
                type: "object",
                required: ["type", "metrics"],
                properties: {
                  type: { const: "metricGrid" },
                  metrics: {
                    type: "array",
                    items: { $ref: "#/$defs/briefMetric" },
                  },
                },
              },
            ],
          },
        },
      },
    },
  },
} as const;

export const briefJsonSchemaText = JSON.stringify(briefJsonSchema, null, 2);
