import { nvdaBrief } from "@/data/nvdaBrief";
import { validateBriefDocument } from "@/lib/briefs/validateBrief";
import { getEvidenceStatusCopy } from "@/lib/evidence/evidenceStatusCopy";
import type { BriefDocument } from "@/types/brief";
import type { GenerateBriefInput, GenerateBriefResult } from "../types";

export async function mockProvider(
  input: GenerateBriefInput,
): Promise<GenerateBriefResult> {
  const ticker = normalizeTicker(input.ticker);
  const companyName = input.companyName?.trim() || getMockCompanyName(ticker);
  const now = formatCstTimestamp();
  const evidencePack = input.evidencePack;
  const secEvidencePack = input.secEvidencePack;
  const irEvidencePack = input.irEvidencePack;
  const researchEvidenceContext = input.researchEvidenceContext;
  const hasEvidencePack = Boolean(evidencePack);
  const hasSecEvidence = Boolean(secEvidencePack);
  const hasIrEvidence = Boolean(irEvidencePack);
  const hasAnyEvidence =
    Boolean(researchEvidenceContext) ||
    hasEvidencePack ||
    hasSecEvidence ||
    hasIrEvidence;
  const evidenceStatus = getEvidenceStatusCopy({
    evidenceLevel: researchEvidenceContext?.evidenceLevel,
    hasSearchEvidence: hasEvidencePack,
    hasSecEvidence,
    hasIrEvidence,
    searchProvider: evidencePack?.searchProvider,
    secProvider: secEvidencePack?.provider,
    irProvider: irEvidencePack?.provider,
  });

  const baseBrief = cloneBrief(nvdaBrief);
  const brief =
    ticker === "NVDA"
      ? baseBrief
      : replaceCompanyTokens(baseBrief, ticker, companyName);

  brief.schemaVersion = "0.1";
  brief.slug = ticker.toLowerCase().replaceAll(".", "-");
  brief.metadata = {
    ...brief.metadata,
    ticker,
    companyName,
    title: `${companyName} / ${ticker} Buy-Side Equity Research Memo`,
    language: input.language === "en" ? "en-US" : "zh-CN",
    isMock: true,
    generatedAt: now,
    updatedAt: now,
    frameworkStatus: "mock-reference-only",
    dataMode: hasAnyEvidence ? "evidence-draft" : "mock",
    brand: "Moki",
    product: "Moki Alpha Brief",
    shareLabel: hasAnyEvidence ? evidenceStatus.label : "LLM Demo Preview",
  };
  brief.hero = {
    ...brief.hero,
    headline: ticker,
    subheadline: companyName,
    badges: hasAnyEvidence
      ? [
          {
            label: evidenceStatus.label,
            tone: "brand",
          },
          {
            label: getMockEvidenceBadgeLabel(input),
            tone: "neutral",
          },
        ]
      : [
          { label: "LLM Demo Preview", tone: "brand" },
          { label: "Mock Provider / No Live Data", tone: "neutral" },
        ],
  };
  brief.cta = {
    ...brief.cta,
    title: "Generate your own Alpha Brief",
    description:
      "Create a Moki Alpha Brief task and review the generated research memo. This preview remains a demo / evidence draft and is not saved.",
    buttonLabel: "Generate Brief",
    buttonHref: "/generate",
  };
  brief.sourceNote = {
    id: "source-note",
    title: "Source & Method Note",
    paragraphs: hasAnyEvidence
      ? [
          buildMockEvidenceSourceNote({
            evidencePack,
            secEvidencePack,
            irEvidencePack,
            researchEvidenceContext,
            now,
          }),
          "Targets, implied returns, and valuation outputs remain simulated framework language unless separately verified by market price, consensus estimates, and manual review.",
        ]
      : [
          "This result was generated by the mock provider to test BriefDocument rendering. It does not represent real investment research.",
          "Search, SEC, Company IR, real-time market price, consensus estimates, database save, and manual verification are not connected.",
        ],
  };
  brief.disclaimer = {
    title: "Disclaimer",
    text: "This page is for research and information reference only and does not constitute investment advice. Current content is Mock / LLM Demo / Evidence Draft and does not represent real-time market data, a formal rating, or personalized advice.",
  };
  brief.evidencePack = evidencePack;
  brief.secEvidencePack = secEvidencePack;
  brief.irEvidencePack = irEvidencePack;
  brief.researchEvidenceContext = researchEvidenceContext;
  brief.evidenceSummary = researchEvidenceContext?.coverage;

  const issues = validateBriefDocument(brief);

  return {
    ok: issues.length === 0,
    provider: "mock",
    model: "mock-provider",
    modelMode: input.modelMode ?? inferModelMode(input.model),
    brief,
    issues,
    isFallback: false,
    error: issues.length ? "Mock provider generated an invalid brief." : undefined,
  };
}

function inferModelMode(model: string | undefined) {
  return model === "deepseek-reasoner" ? "reasoner" : "chat";
}

function getMockEvidenceBadgeLabel(input: GenerateBriefInput) {
  if (input.secEvidencePack?.provider === "mock" && input.irEvidencePack?.provider === "mock") {
    return "Mock SEC + IR Evidence";
  }
  if (input.secEvidencePack?.provider === "mock") return "Mock SEC Evidence";
  if (input.irEvidencePack?.provider === "mock") return "Mock IR Evidence";
  return "Evidence Draft";
}

function buildMockEvidenceSourceNote({
  evidencePack,
  secEvidencePack,
  irEvidencePack,
  researchEvidenceContext,
  now,
}: {
  evidencePack: GenerateBriefInput["evidencePack"];
  secEvidencePack: GenerateBriefInput["secEvidencePack"];
  irEvidencePack: GenerateBriefInput["irEvidencePack"];
  researchEvidenceContext: GenerateBriefInput["researchEvidenceContext"];
  now: string;
}) {
  const parts: string[] = [];
  const evidenceLevel =
    researchEvidenceContext?.evidenceLevel ||
    (evidencePack && secEvidencePack && irEvidencePack
      ? "search-sec-and-ir"
      : evidencePack && secEvidencePack
        ? "search-and-sec"
        : evidencePack && irEvidencePack
          ? "search-and-ir"
          : secEvidencePack && irEvidencePack
            ? "sec-and-ir"
            : secEvidencePack
              ? "sec-only"
              : evidencePack
                ? "search-only"
                : irEvidencePack
                  ? "ir-only"
                  : "none");

  if (evidenceLevel === "search-sec-and-ir") {
    parts.push(
      "Search + SEC + IR Evidence Draft: search evidence, SEC companyfacts / submissions, and Company IR / earnings-release evidence are attached.",
    );
  } else if (evidenceLevel === "search-and-sec") {
    parts.push(
      "Search + SEC Evidence Draft: search evidence and SEC companyfacts / submissions are attached.",
    );
  } else if (evidenceLevel === "search-and-ir") {
    parts.push(
      "Search + IR Evidence Draft: search evidence and Company IR / earnings-release evidence are attached.",
    );
  } else if (evidenceLevel === "sec-and-ir") {
    parts.push(
      "SEC + IR Evidence Draft: SEC companyfacts / submissions and Company IR / earnings-release evidence are attached.",
    );
  } else if (evidenceLevel === "ir-only") {
    parts.push("IR Evidence Draft: Company IR / earnings-release evidence is attached.");
  }

  if (evidenceLevel !== "none") {
    parts.push(
      `Research Evidence Context: evidenceLevel=${evidenceLevel}; dataMode=evidence-draft.`,
    );
  }

  if (evidencePack) {
    parts.push(
      `Search Evidence Draft: provider=${evidencePack.searchProvider || "mock"}; sourceCount=${evidencePack.newsItems?.length || evidencePack.sources.length || 0}; retrievedAt=${evidencePack.asOf || now}.`,
    );
  }

  if (secEvidencePack) {
    parts.push(
      `SEC Evidence Draft: provider=${secEvidencePack.provider}; CIK=${secEvidencePack.cik}; recentFilings=${secEvidencePack.recentFilings.length}; fiscalFacts=${secEvidencePack.fiscalFacts.length}; asOf=${secEvidencePack.asOf || now}.`,
    );
  }

  if (irEvidencePack) {
    parts.push(
      `IR Evidence Draft: provider=${irEvidencePack.provider}; sourceCount=${irEvidencePack.irItems.length}; retrievedAt=${irEvidencePack.asOf || now}.`,
    );
  } else if (evidenceLevel !== "none") {
    parts.push("Company IR / earnings-release evidence is not connected.");
  }

  parts.push(
    "Current scope still excludes real-time market price, consensus estimates, database save, manual verification, PDF full-text parsing, and transcript full-text parsing. Company IR evidence is management-commentary / business-update context only and must not be treated as SEC official financial facts, consensus, or real-time market data.",
  );

  return parts.join(" ");
}

function normalizeTicker(ticker: string) {
  return ticker.trim().toUpperCase();
}

function getMockCompanyName(ticker: string) {
  if (ticker === "NVDA") return "NVIDIA";
  return `${ticker} Demo Company`;
}

function cloneBrief(brief: BriefDocument) {
  return JSON.parse(JSON.stringify(brief)) as BriefDocument;
}

function replaceCompanyTokens<T>(value: T, ticker: string, companyName: string): T {
  if (typeof value === "string") {
    return value
      .replaceAll("NVIDIA", companyName)
      .replaceAll("NVDA", ticker) as T;
  }

  if (Array.isArray(value)) {
    return value.map((item) =>
      replaceCompanyTokens(item, ticker, companyName),
    ) as T;
  }

  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, child]) => [
        key,
        replaceCompanyTokens(child, ticker, companyName),
      ]),
    ) as T;
  }

  return value;
}

function formatCstTimestamp() {
  const value = new Intl.DateTimeFormat("sv-SE", {
    timeZone: "Asia/Shanghai",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  }).format(new Date());

  return `${value} CST`;
}
