import { nvdaBrief } from "@/data/nvdaBrief";
import { validateBriefDocument } from "@/lib/briefs/validateBrief";
import { getEvidenceStatusCopy } from "@/lib/evidence/evidenceStatusCopy";
import type { BriefDocument } from "@/types/brief";
import type { GenerateBriefInput, GenerateBriefResult } from "../types";

export async function mockProvider(
  input: GenerateBriefInput,
): Promise<GenerateBriefResult> {
  const ticker = normalizeTicker(input.ticker);
  const companyName = input.companyName?.trim() || getMockCompanyName(ticker);
  const now = formatCstTimestamp();
  const evidencePack = input.evidencePack;
  const secEvidencePack = input.secEvidencePack;
  const irEvidencePack = input.irEvidencePack;
  const marketEvidencePack = input.marketEvidencePack;
  const consensusEvidencePack = input.consensusEvidencePack;
  const researchEvidenceContext = input.researchEvidenceContext;
  const hasEvidencePack = Boolean(evidencePack);
  const hasSecEvidence = Boolean(secEvidencePack);
  const hasIrEvidence = Boolean(irEvidencePack);
  const hasMarketEvidence = Boolean(marketEvidencePack);
  const hasConsensusEvidence = Boolean(consensusEvidencePack);
  const hasAnyEvidence =
    Boolean(researchEvidenceContext) ||
    hasEvidencePack ||
    hasSecEvidence ||
    hasIrEvidence ||
    hasMarketEvidence ||
    hasConsensusEvidence;
  const evidenceStatus = getEvidenceStatusCopy({
    evidenceLevel: researchEvidenceContext?.evidenceLevel,
    hasSearchEvidence: hasEvidencePack,
    hasSecEvidence,
    hasIrEvidence,
    hasMarketEvidence,
    hasConsensusEvidence,
    searchProvider: evidencePack?.searchProvider,
    secProvider: secEvidencePack?.provider,
    irProvider: irEvidencePack?.provider,
    marketProvider: marketEvidencePack?.provider,
    consensusProvider: consensusEvidencePack?.provider,
  });

  const baseBrief = cloneBrief(nvdaBrief);
  const brief =
    ticker === "NVDA"
      ? baseBrief
      : replaceCompanyTokens(baseBrief, ticker, companyName);

  brief.schemaVersion = "0.1";
  brief.slug = ticker.toLowerCase().replaceAll(".", "-");
  brief.metadata = {
    ...brief.metadata,
    ticker,
    companyName,
    title: `${companyName} / ${ticker} Buy-Side Equity Research Memo`,
    language: input.language === "en" ? "en-US" : "zh-CN",
    isMock: true,
    generatedAt: now,
    updatedAt: now,
    frameworkStatus: "mock-reference-only",
    dataMode: hasAnyEvidence ? "evidence-draft" : "mock",
    brand: "Moki",
    product: "Moki Alpha Brief",
    shareLabel: hasAnyEvidence ? evidenceStatus.label : "LLM Demo Preview",
  };
  brief.hero = {
    ...brief.hero,
    headline: ticker,
    subheadline: companyName,
    badges: hasAnyEvidence
      ? [
          {
            label: evidenceStatus.label,
            tone: "brand",
          },
          {
            label: getMockEvidenceBadgeLabel(input),
            tone: "neutral",
          },
        ]
      : [
          { label: "LLM Demo Preview", tone: "brand" },
          { label: "Mock Provider / No Live Data", tone: "neutral" },
        ],
  };
  brief.cta = {
    ...brief.cta,
    title: "Generate your own Alpha Brief",
    description:
      "Create a Moki Alpha Brief task and review the generated research memo. This preview remains a demo / evidence draft and is not saved.",
    buttonLabel: "Generate Brief",
    buttonHref: "/generate",
  };
  brief.sourceNote = {
    id: "source-note",
    title: "Source & Method Note",
    paragraphs: hasAnyEvidence
      ? [
          buildMockEvidenceSourceNote({
            evidencePack,
            secEvidencePack,
            irEvidencePack,
            marketEvidencePack,
            consensusEvidencePack,
            researchEvidenceContext,
            now,
          }),
          "Targets, implied returns, and valuation outputs remain simulated framework language. Do not treat this brief as a formal target price, formal rating, or investment advice.",
        ]
      : [
          "This result was generated by the mock provider to test BriefDocument rendering. It does not represent real investment research.",
          "Search, SEC, Company IR, real-time market price, consensus estimates, database save, and manual verification are not connected.",
        ],
  };
  brief.disclaimer = {
    title: "Disclaimer",
    text: "This page is for research and information reference only and does not constitute investment advice. Current content is Mock / LLM Demo / Evidence Draft and does not represent real-time market data, an official investment rating, or personalized advice.",
  };
  brief.evidencePack = evidencePack;
  brief.secEvidencePack = secEvidencePack;
  brief.irEvidencePack = irEvidencePack;
  brief.marketEvidencePack = marketEvidencePack;
  brief.consensusEvidencePack = consensusEvidencePack;
  brief.researchEvidenceContext = researchEvidenceContext;
  brief.evidenceSummary = researchEvidenceContext?.coverage;

  const issues = validateBriefDocument(brief);

  return {
    ok: issues.length === 0,
    provider: "mock",
    model: "mock-provider",
    modelMode: input.modelMode ?? inferModelMode(input.model),
    brief,
    issues,
    isFallback: false,
    error: issues.length ? "Mock provider generated an invalid brief." : undefined,
  };
}

function inferModelMode(model: string | undefined) {
  return model === "deepseek-reasoner" ? "reasoner" : "chat";
}

function getMockEvidenceBadgeLabel(input: GenerateBriefInput) {
  if (input.consensusEvidencePack?.provider === "mock") return "Mock Consensus Evidence";
  if (input.marketEvidencePack?.provider === "mock") return "Mock Market Evidence";
  if (input.secEvidencePack?.provider === "mock" && input.irEvidencePack?.provider === "mock") {
    return "Mock SEC + IR Evidence";
  }
  if (input.secEvidencePack?.provider === "mock") return "Mock SEC Evidence";
  if (input.irEvidencePack?.provider === "mock") return "Mock IR Evidence";
  return "Evidence Draft";
}

function buildMockEvidenceSourceNote({
  evidencePack,
  secEvidencePack,
  irEvidencePack,
  marketEvidencePack,
  consensusEvidencePack,
  researchEvidenceContext,
  now,
}: {
  evidencePack: GenerateBriefInput["evidencePack"];
  secEvidencePack: GenerateBriefInput["secEvidencePack"];
  irEvidencePack: GenerateBriefInput["irEvidencePack"];
  marketEvidencePack: GenerateBriefInput["marketEvidencePack"];
  consensusEvidencePack: GenerateBriefInput["consensusEvidencePack"];
  researchEvidenceContext: GenerateBriefInput["researchEvidenceContext"];
  now: string;
}) {
  const parts: string[] = [];
  const evidenceLevel =
    researchEvidenceContext?.evidenceLevel ||
    (evidencePack && secEvidencePack && irEvidencePack && marketEvidencePack && consensusEvidencePack
      ? "search-sec-ir-market-and-consensus"
      : evidencePack && secEvidencePack && irEvidencePack && marketEvidencePack
      ? "search-sec-ir-and-market"
      : marketEvidencePack && consensusEvidencePack
        ? "market-and-consensus"
      : evidencePack && secEvidencePack && marketEvidencePack
        ? "search-sec-and-market"
        : evidencePack && irEvidencePack && marketEvidencePack
          ? "search-ir-and-market"
          : secEvidencePack && irEvidencePack && marketEvidencePack
            ? "sec-ir-and-market"
            : evidencePack && secEvidencePack && irEvidencePack
      ? "search-sec-and-ir"
            : evidencePack && secEvidencePack
              ? "search-and-sec"
              : evidencePack && irEvidencePack
                ? "search-and-ir"
                : evidencePack && marketEvidencePack
                  ? "search-and-market"
                  : secEvidencePack && irEvidencePack
                    ? "sec-and-ir"
                    : secEvidencePack && marketEvidencePack
                      ? "sec-and-market"
                      : irEvidencePack && marketEvidencePack
                        ? "ir-and-market"
                          : secEvidencePack
                            ? "sec-only"
                          : evidencePack
                            ? "search-only"
                            : irEvidencePack
                              ? "ir-only"
                              : marketEvidencePack
                                ? "market-only"
                                : consensusEvidencePack
                                  ? "consensus-only"
                                : "none");

  if (evidenceLevel === "search-sec-ir-market-and-consensus") {
    parts.push(
      "Search + SEC + IR + Market + Consensus Evidence Draft: search evidence, SEC companyfacts / submissions, Company IR / earnings-release evidence, third-party free market evidence, and mock consensus estimate context are attached.",
    );
  } else if (evidenceLevel === "search-sec-ir-and-market") {
    parts.push(
      "Search + SEC + IR + Market Evidence Draft: search evidence, SEC companyfacts / submissions, Company IR / earnings-release evidence, and third-party free market evidence are attached.",
    );
  } else if (evidenceLevel === "search-sec-and-ir") {
    parts.push(
      "Search + SEC + IR Evidence Draft: search evidence, SEC companyfacts / submissions, and Company IR / earnings-release evidence are attached.",
    );
  } else if (evidenceLevel === "market-only") {
    parts.push("Market Evidence Draft: third-party free market evidence is attached.");
  } else if (evidenceLevel === "consensus-only") {
    parts.push("Consensus Evidence Draft: mock revenue / EPS analyst estimate context is attached.");
  } else if (evidenceLevel.includes("consensus")) {
    parts.push(
      "Consensus Evidence Draft: mock revenue / EPS analyst estimate context is attached for expectation-gap analysis.",
    );
  } else if (evidenceLevel.includes("market")) {
    parts.push(
      "Market Evidence Draft: third-party free market evidence is attached for price, volume, and recent daily kline context.",
    );
  } else if (evidenceLevel === "search-and-sec") {
    parts.push(
      "Search + SEC Evidence Draft: search evidence and SEC companyfacts / submissions are attached.",
    );
  } else if (evidenceLevel === "search-and-ir") {
    parts.push(
      "Search + IR Evidence Draft: search evidence and Company IR / earnings-release evidence are attached.",
    );
  } else if (evidenceLevel === "sec-and-ir") {
    parts.push(
      "SEC + IR Evidence Draft: SEC companyfacts / submissions and Company IR / earnings-release evidence are attached.",
    );
  } else if (evidenceLevel === "ir-only") {
    parts.push("IR Evidence Draft: Company IR / earnings-release evidence is attached.");
  }

  if (evidenceLevel !== "none") {
    parts.push(
      `Research Evidence Context: evidenceLevel=${evidenceLevel}; dataMode=evidence-draft.`,
    );
  }

  if (evidencePack) {
    parts.push(
      `Search Evidence Draft: provider=${evidencePack.searchProvider || "mock"}; sourceCount=${evidencePack.newsItems?.length || evidencePack.sources.length || 0}; retrievedAt=${evidencePack.asOf || now}.`,
    );
  }

  if (secEvidencePack) {
    parts.push(
      `SEC Evidence Draft: provider=${secEvidencePack.provider}; CIK=${secEvidencePack.cik}; recentFilings=${secEvidencePack.recentFilings.length}; fiscalFacts=${secEvidencePack.fiscalFacts.length}; asOf=${secEvidencePack.asOf || now}.`,
    );
  }

  if (irEvidencePack) {
    parts.push(
      `IR Evidence Draft: provider=${irEvidencePack.provider}; sourceCount=${irEvidencePack.irItems.length}; retrievedAt=${irEvidencePack.asOf || now}.`,
    );
  } else if (evidenceLevel !== "none") {
    parts.push("Company IR / earnings-release evidence is not connected.");
  }

  if (marketEvidencePack) {
    const quote = marketEvidencePack.quote;
    parts.push(
      `Market Evidence Draft: marketProvider=${marketEvidencePack.provider}; providerChain=${marketEvidencePack.providerChain?.join(" -> ") || marketEvidencePack.provider}; retrievedAt=${quote?.retrievedAt || marketEvidencePack.asOf || now}; marketTimestamp=${quote?.marketTimestamp || "N/A"}; sourceCount=${marketEvidencePack.sources.length}; priceHistoryPoints=${marketEvidencePack.priceHistory?.length || 0}. Provider may be stock-api / global-stock-data / mock fallback. Free public market data may be delayed, incomplete, field-limited, or unavailable.`,
    );
  }

  if (consensusEvidencePack) {
    parts.push(
      `Consensus Evidence Draft: consensusProvider=${consensusEvidencePack.provider}; providerChain=${consensusEvidencePack.providerChain?.join(" -> ") || consensusEvidencePack.provider}; period=${consensusEvidencePack.period}; asOf=${consensusEvidencePack.asOf || now}; estimateCount=${consensusEvidencePack.estimates.length}; dataMode=evidence-draft; not verified-real-data; not investment advice. Consensus provider=mock and consensus is mock evidence. Consensus evidence is not SEC actual data and not market price data.`,
    );
  }

  parts.push(
    consensusEvidencePack
      ? "Current scope still excludes login, editing, history versions, manual verification, PDF full-text parsing, transcript full-text parsing, and real FMP / Finnhub consensus providers. Company IR evidence is management-commentary / business-update context only and must not be treated as SEC official financial facts or consensus. Market evidence is third-party free market context only and is not verification-grade data, a formal trading quote, or investment advice. Consensus evidence is mock-only context and must not be treated as SEC actual data."
      : marketEvidencePack
        ? "Current scope still excludes consensus estimates, manual verification, PDF full-text parsing, and transcript full-text parsing. Company IR evidence is management-commentary / business-update context only and must not be treated as SEC official financial facts or consensus. Market evidence is third-party free market context only and is not verification-grade data, a formal trading quote, or investment advice."
        : "Current scope still excludes real-time market price, consensus estimates, manual verification, PDF full-text parsing, and transcript full-text parsing. Company IR evidence is management-commentary / business-update context only and must not be treated as SEC official financial facts or consensus.",
  );

  return parts.join(" ");
}

function normalizeTicker(ticker: string) {
  return ticker.trim().toUpperCase();
}

function getMockCompanyName(ticker: string) {
  if (ticker === "NVDA") return "NVIDIA";
  return `${ticker} Demo Company`;
}

function cloneBrief(brief: BriefDocument) {
  return JSON.parse(JSON.stringify(brief)) as BriefDocument;
}

function replaceCompanyTokens<T>(value: T, ticker: string, companyName: string): T {
  if (typeof value === "string") {
    return value
      .replaceAll("NVIDIA", companyName)
      .replaceAll("NVDA", ticker) as T;
  }

  if (Array.isArray(value)) {
    return value.map((item) =>
      replaceCompanyTokens(item, ticker, companyName),
    ) as T;
  }

  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, child]) => [
        key,
        replaceCompanyTokens(child, ticker, companyName),
      ]),
    ) as T;
  }

  return value;
}

function formatCstTimestamp() {
  const value = new Intl.DateTimeFormat("sv-SE", {
    timeZone: "Asia/Shanghai",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  }).format(new Date());

  return `${value} CST`;
}
